Первая попытка сдачи
Anton-Phedorenko/java-shareit pull request #1
Opened 2022-12-27 11:07 UTC by Anton-Phedorenko

Привет,Денис! Отправляю проект на проверку 
Ох и испугался я сперва,когда тесты на гитхабе не прошли из за code style

2023-01-02 11:38 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-01-02 11:38 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dao/ItemDaoImpl.java
>          else return Collections.emptyList();
Не экономим на `{}`

2023-01-02 11:38 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/dao/UserDao.java
>      UserDto findById(Long id);
`UserDto findById(Long id); -> Optional<UserDto> findById(Long id);`

Сразу делаем одиночные выборки с Optional

2023-01-16 10:18 UTC, Anton-Phedorenko commented on src/main/java/ru/practicum/shareit/user/dao/UserDao.java
>      UserDto findById(Long id);
Сделал

2023-01-16 11:32 UTC, Anton-Phedorenko commented
Привет,Денис,отправляю проект на проверку)

2023-01-16 18:33 UTC, FanaticFiz approved these changes

2023-01-16 18:33 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        ItemDto updateItem = itemDao.findById(id).get();
Нельзя get без проверки... нужно использовать `orElseThrow`

2023-01-16 18:33 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/dao/UserDaoImpl.java
> +        return id < 1 || id == null ? null : users.values().stream().filter(u -> u.getId().equals(id)).findFirst();
Так не пойдет... проверить id нужно было еще в контролере - это его зона ответственности!

2023-02-06 12:22 UTC, merged