первая попытка сдачи
Anton-Phedorenko/java-shareit pull request #2
Opened 2023-02-19 11:09 UTC by Anton-Phedorenko

Привет,Денис,отправляю проект на проверку)

2023-02-19 19:18 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-02-19 19:18 UTC, FanaticFiz commented on pom.xml
> +         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
Каталог `/db` следует добавить в gitignore, не комитим бинарные файлы.

2023-02-19 19:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        System.out.println(132);
Почему не логгер?

2023-02-19 19:18 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +CREATE TABLE if not exists booking(
Криво, косо...

2023-02-19 19:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private Status status;
Не хватает отступов между полями...

Не все свойства из БД отражены в модели, например ограничение длинны в 20 символов.
`status varchar(20),`

2023-02-19 19:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query("select b from Booking b join Item i on i.id = b.item.id " +
Оформляй запросы, набирая команды SQL в верхнем регистре: SELECT

2023-02-19 19:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    BookingDto findById(Long bookingId, Long userId);
В сервисах давай использовать глагол `get`
А в репозиториях `find`

2023-02-19 19:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemDto.getId() == null) throw new NotFoundException("Вещь не может быть найдена");
Не экономим на `{}`!
Добавляем больше информации: какая вещь не может быть найдена?

2023-02-19 19:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +//    User update(User user);
мусор

2023-02-19 19:18 UTC, FanaticFiz commented on src/main/resources/application.properties
> +spring.config.activate.on-profile=ci,test,default
Почему  файла свойств всё еще не в формате `YAML` ?

`application.properties -> application.yml`

2023-02-20 11:14 UTC, Anton-Phedorenko commented on src/main/resources/schema.sql
> +CREATE TABLE if not exists booking(
поправил

2023-02-20 11:42 UTC, Anton-Phedorenko commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query("select b from Booking b join Item i on i.id = b.item.id " +
сделал

2023-02-20 12:08 UTC, Anton-Phedorenko commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    BookingDto findById(Long bookingId, Long userId);
хорошо

2023-02-20 12:09 UTC, Anton-Phedorenko commented on src/main/resources/application.properties
> +spring.config.activate.on-profile=ci,test,default
сделал

2023-02-20 13:05 UTC, Anton-Phedorenko commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private Status status;
поправил этот момент
К слову сказать, у меня была небольшая проблема в начале,когда при запуске приложения создавались таблицы и связи исходя из моих классов,а файл schema.sql участия в этом не принимал. Я так понимаю на такой случай должно существовать однозначное соответствие между файлом,где мы определяем таблицы и связи и между тем,как мы делаем это в классах? Чтобы и так и так все работало исправно?

2023-02-20 13:10 UTC, Anton-Phedorenko commented
Привет, Денис! Поработал над замечаниями,отправляю повторно

2023-02-20 13:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private Status status;
Да, есть такой режим - он удобен в тестах например.
Но и без него, в целом, всегда нужно стремиться к тому чтобы поддерживать порядок и соответствие/согласованность.

А когда эту работу можно кому-то поручить, то грех за этим не проследить и не поправить чужими руками )))

2023-02-20 19:47 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-02-20 19:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private Status status;
status varchar(20) !!!
Почему 300 ?

2023-02-20 19:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Такого заказа не существует"));
Какого заказа не существует?
Больше информации, она вот у тебя под самым носом, просто добавь её ))

2023-02-20 19:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                booking.setStatus(Status.APPROVED);
Импортируй статики... 

`import static ru.practicum.shareit.booking.Status.APPROVED;`

Код будет короче и читабельнее
`booking.setStatus(APPROVED);`

2023-02-20 19:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/comment/service/CommentServiceImpl.java
> +        } else {
Немного отрефакторить...
- инвертировать условие
- избавиться от else

```
        if (bookings.size() == 0) {
            throw new BadRequestException("Предмет не бронировался или ожидает бронирования");
        }
        
        Comment comment = commentRepository.save(CommentMapper.toComment(commentDto));
        comment.setAuthor(bookings.get(0).getBooker());
        comment.setItem(item);
        
        return CommentMapper.toCommentDto(comment);
```

2023-02-20 19:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private final UserRepository userRepository;
userRepository - не используется!

2023-02-20 19:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserController.java
>          if (id < 0 || id == null) throw new BadRequestException("Некорректный id");
Не правильная последовательность проверки... поменять местами 
`id < 0 || id == null` -> `id == null || id < 0`

2023-02-20 19:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return UserMapper.toUserDto(userService.create(UserMapper.toUser(userDto)));
```
    @PostMapping
    public UserDto create(@RequestBody @Valid UserDto userDto) {
        User user = userService.create(toUser(userDto));
        
        return toUserDto(user);
    }
```

Лучше в две строки.

2023-02-20 19:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        if (id == null || id < 0) throw new BadRequestException("Некорректный id пользователя");
Не экономим на `{}`, в Java это не принято...

2023-02-20 19:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return UserMapper.toUserDto(userService.update(UserMapper.toUser(userDto)));
Есть хорошая практика делать отступ, в виде пустой строки, перед `return`.

Это выделяет точку выхода из метода визуально.
Есть только одно исключение: если метод начался сразу с return то отступ делать не нужно.

2023-02-20 19:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return updateUserIfExist(user);
Не очень понятно зачем было оборачивать еще и приватным методом?
Этот метод не переиспользуется, получается лишний...

2023-02-20 19:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return userRepository.findById(id).orElseThrow(() -> new NotFoundException("Пользователь не найден"));
```
    @Override
    public User getById(Long id) {
        return userRepository.findById(id)
                             .orElseThrow(() -> new NotFoundException("Не найден пользователь с id: " + id));
    }
```

Комбинируя код в цепочки, лучше каждую отдельную операцию переносить на отдельную строку.

2023-02-20 19:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>          if (user.getEmail().isEmpty() || user.getEmail() == null) throw new RuntimeException();
Снова неверная последовательность проверки и не хватает `{}`

2023-02-20 19:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return Optional.ofNullable(getAll()
Намудрил лишнего тут!
`Optional<T> findFirst();` - возвращает Optional поэтому убери лишний ofNullable!

Но этот метод в целом, концептуально неверен!
Нельзя брать из БД всё, а потом фильтровать. Надо пользоваться SQL и выбирать из БД нужное - т.е. `findUserByEmail` это должен быть метод в репозитории!

2023-02-20 19:47 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +create table if not exists users
- Отступы между описанием каждой таблички нужны
- бардак в том что не все команды SQL в верхнем регистре: CREATE TABLE
- выравнивание было бы очень уместно
```
    id           int generated always as identity primary key,
    name         varchar(300),
    description  varchar(300),
    is_available boolean,
    owner_id     int,
    request_id   int,
```

2023-02-22 08:44 UTC, Anton-Phedorenko commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private Status status;
ой,поправил:D

2023-02-22 08:47 UTC, Anton-Phedorenko commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                booking.setStatus(Status.APPROVED);
удобно)

2023-02-22 08:54 UTC, Anton-Phedorenko commented on src/main/java/ru/practicum/shareit/comment/service/CommentServiceImpl.java
> +        } else {
сделал

2023-02-22 09:15 UTC, Anton-Phedorenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
>          if (id < 0 || id == null) throw new BadRequestException("Некорректный id");
Интересный момент,это правило хорошего тона,сначала проверять на null? Просто учитывая,что используется " II ",
на производительность такая перемена мест влиять не должна. Вообще вот эти вопросы с тем,как принято оформлять код, как назвать переменную и прочее занимают меня в последнее время,только везде требования,как я понимаю разные и это грустно. Хотелось бы иметь на этот случай некий универсальный гайд :D

2023-02-22 09:33 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserController.java
>          if (id < 0 || id == null) throw new BadRequestException("Некорректный id");
В данном случае это бессмысленно же... если сначала проверить что `id < 0` то уже точно id не null.
Поэтому, если нужны обе проверки, то сначала проверим что не null, а только потом что меньше 0

Такое, обычно хорошо отслеживает и показывает IDE

2023-02-22 09:37 UTC, Anton-Phedorenko commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return updateUserIfExist(user);
в этом методе реализовано, как я вычитал в интернете Partial Update. В общем,только те данные,которые надо обновить - мы обновляем. Поскольку я видел,что для этого используются библиотеки и специальный подход,а я делаю это руками пока что - я решил вынести это в отдельный метод,так что с если позволишь,давай оставим)

2023-02-22 10:19 UTC, Anton-Phedorenko commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return Optional.ofNullable(getAll()
сделано. Вот кстати еще одна вещь, которая занимает меня - это,если можно так выразиться,оптимальные запросы в бд. Но пока что к сожалению ошибаюсь в самых простецких вещах(

2023-02-22 10:22 UTC, Anton-Phedorenko commented on src/main/resources/schema.sql
> +create table if not exists users
сделал,но сделал руками, в настройках codestyle sql вроде все нормально,но как делаю ctrl+alt+L ,тут же файл становится еще более некрасивым

2023-02-22 10:32 UTC, Anton-Phedorenko commented
Привет! Отправляю на проверку

2023-02-22 11:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return updateUserIfExist(user);
Я просто подчеркнул что этот код мог бы быть и непосредственно в методе `public User update(User user)`

2023-02-22 11:08 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return Optional.ofNullable(getAll()
Ну прям об "оптимальности" можно и диссертацию защитить...  ))
Просто будет отдельный метод со своим `WHERE email = 'someEmail'`

Главное это начать делать именно так, а не выбирать из БД все... потом отфильтровывая в коде нужное.

2023-02-22 11:09 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +create table if not exists users
Возможно не проставлено что это именно синтаксис postgresql

2023-02-22 19:13 UTC, FanaticFiz approved these changes

2023-02-24 10:25 UTC, merged