Add item requests
Anton-Phedorenko/java-shareit pull request #5
Opened 2023-03-07 20:26 UTC by Anton-Phedorenko

Привет,Денис,надеюсь в этот раз изменения в файлах видны)

2023-03-08 16:40 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-03-08 16:40 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/ShareItApp.java
>  public class ShareItApp {
Не должны коммитится файлы базы данных 
![image](https://user-images.githubusercontent.com/3994663/223771839-fdada17a-6d0b-4f0a-b27f-a7dea5285bb3.png)

Нужно удалить их и добавить в `gitignore`

2023-03-08 16:40 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        return toRequestDto(requestRepository.save(itemRequest));
Не прячь основное действие `save` где то в строке другого кода...
Оно достойно отдельной строки кода.

И второе.
Есть хорошая практика делать отступ, в виде пустой строки, перед `return`.
Это выделяет точку выхода из метода визуально.
Есть только одно исключение: если метод начался сразу с return то отступ делать не нужно.

2023-03-08 16:40 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +//    @Override
???

2023-03-08 16:40 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +create table if not exists request
Нужно подравнять весь файл

```
create table if not exists request
(
    id           int generated always as identity primary key,
    description  varchar(300),
    requestor_id int,
    created      TIMESTAMP,
    constraint fk_request_to_users foreign key (requestor_id) references users (id)
);
```

2023-03-09 10:20 UTC, Anton-Phedorenko commented on src/main/java/ru/practicum/shareit/ShareItApp.java
>  public class ShareItApp {
Странно,ведь папка db есть в gitignore

2023-03-09 10:21 UTC, Anton-Phedorenko commented on src/main/resources/schema.sql
> +create table if not exists request
отметил диалект,теперь вроде нормально должно быть

2023-03-09 10:37 UTC, Anton-Phedorenko commented
Привет,поработал над замечаниями)

2023-03-10 18:07 UTC, FanaticFiz approved these changes

2023-03-12 10:12 UTC, merged